const FILM_DURATION = 40;
const ADD_TWO_CARDS = 2;
const ADD_THREE_CARDS = 3;
const INITIAL_COUNT_OF_CARDS_IS_FIVE = 5;
const INITIAL_COUNT_OF_CARDS_IS_EIGHT = 8;
const INITIAL_COUNT_OF_CARDS_IS_TWELVE = 12;

export {
  FILM_DURATION,
  ADD_TWO_CARDS,
  ADD_THREE_CARDS,
  INITIAL_COUNT_OF_CARDS_IS_FIVE,
  INITIAL_COUNT_OF_CARDS_IS_EIGHT,
  INITIAL_COUNT_OF_CARDS_IS_TWELVE,
};